authapp/urls.py
from django.urls import path, re_path
import authapp.views as authapp


app_name = 'authapp'

urlpatterns = [
    path('login/', authapp.login, name='login'),
    path('logout/', authapp.logout, name='logout'),
    path('register/', authapp.register, name='register'),
    path('edit/', authapp.edit, name='edit'),

    re_path(r'^verify/(?P<email>.+)/(?P<activation_key>\w+)/$', authapp.verify, name='verify'),
    # path('verify/<email>/<activation_key>/', authapp.verify, name='verify'),
]

basketapp/urls.py
from django.urls import path
import basketapp.views as basketapp


app_name = 'basketapp'

urlpatterns = [
    path('', basketapp.basket, name='view'),
    path('add/<int:pk>/', basketapp.basket_add, name='add'),
    path('edit/<int:pk>/<int:quantity>/', basketapp.basket_edit, name='edit'),
    path('remove/<int:pk>)/', basketapp.basket_remove, name='remove'),
]

geekshop/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls import include
# from django.contrib import admin
from django.urls import path, re_path
from mainapp import views

urlpatterns = [
    re_path('^$', views.main, name="main"),
    path('', include('social_django.urls', namespace='social')),
    path('contacts/', views.contacts, name="contacts"),
    path('gallery/', views.gallery, name="gallery"),
    path('product/<int:pk>/', views.product, name="product"),  # эту строчку можно перенести в namespace='products'

    # namespaces
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('basket/', include('basketapp.urls', namespace='basket')),
    re_path(r'^order/', include('ordersapp.urls', namespace='order')),
    path('admin/', include('adminapp.urls', namespace='admin')),

    # нет в меню
    path('cart/', views.cart, name="cart"),

    # path('catalog/', views.catalog, name="catalog"),
    # path('categories/', views.categories, name="categories"),
    # path('product/0/', views.products, name="catalog"),
    # path('admin_old/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

if settings.DEBUG:
    import debug_toolbar

    urlpatterns += [re_path(r'^__debug__/', include(debug_toolbar.urls))]

mainapp/urls.py
from django.urls import path

import mainapp.views as mainapp

app_name = 'mainapp'

urlpatterns = [
   path('category/0/', mainapp.products, name='index'),
   path('category/<int:pk>/', mainapp.products, name='category'),
   path('category/<int:pk>/<int:page>/', mainapp.products, name='page'),
   path('product/<int:pk>/', mainapp.product, name='product'),
]

path('', mainapp.products, name='index'),
# path('category/<int:pk>/page/<int:page>/', mainapp.products, name='page'),
# path('page/<int:page>/', mainapp.products, name='page'),
# path('<int:pk>/', mainapp.products, name='product'),
# path('0/', mainapp.products, name="catalog"),

mainapp/models.py
from django.db import models


class ProductCategory(models.Model):
    name = models.CharField(verbose_name='название категории', max_length=64, unique=True)
    description = models.TextField(verbose_name='описание категории', blank=True)
    is_active = models.BooleanField(db_index=True, verbose_name='активная', default=True)

    def __str__(self):
        return self.name


class Product(models.Model):
    category = models.ForeignKey(ProductCategory, on_delete=models.CASCADE)
    name = models.CharField(verbose_name='имя продукта', max_length=128)
    image = models.ImageField(upload_to='products_images/big', blank=True)
    image_small = models.ImageField(upload_to='products_images/small', blank=True)
    short_desc = models.CharField(verbose_name='краткое описание продукта', max_length=60, blank=True)
    description = models.TextField(verbose_name='описание продукта', blank=True)
    price = models.DecimalField(verbose_name='цена продукта', max_digits=8, decimal_places=2, default=0)
    quantity = models.PositiveIntegerField(verbose_name='количество на складе', default=0)
    is_active = models.BooleanField(db_index=True, verbose_name='активен', default=True)

    def __str__(self):
        return f'{self.name} ({self.category.name})'

    @staticmethod
    def get_items():
        return Product.objects.filter(is_active=True).order_by('category', 'name')

mainapp/views.py
import os
import json
import random
from django.conf import settings
from django.shortcuts import render, get_object_or_404
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.core.cache import cache
from django.views.decorators.cache import cache_page
from .models import Product, ProductCategory


def main(request):
    context = {
        'title': "Магазин",
    }
    return render(request, 'mainapp/index.html', context)


@cache_page(3600)
def contacts(request):
    context = {
        'title': "Контакты",
    }
    return render(request, 'mainapp/contacts.html', context)


def gallery(request):
    with open(os.path.join(settings.BASE_DIR, 'static/db_goods.json'), "r", encoding="utf-8") as read_file:
        goods = json.load(read_file)
    context = {
        'title': "Галерея",
        'goods': goods,
    }
    return render(request, 'mainapp/gallery.html', context)


def cart(request):
    context = {
        'title': "Корзина",
    }
    return render(request, 'mainapp/cart.html', context)


def categories(request):
    _categories = get_links_menu()
    context = {
        'title': "Категории",
        'categories': _categories,
    }
    return render(request, 'mainapp/categories.html', context)


def product(request, pk=None):
    _product = get_product(pk)
    context = {
        'title': _product.name,
        'links_menu': get_links_menu(),
        'product': _product,
    }
    return render(request, 'mainapp/product.html', context)


def products(request, pk=None, page=1):

    title = 'продукты'
    links_menu = get_links_menu()

    if (pk is None) or (pk == ""):
        pk = 0

    if pk == 0:
        _products = get_products_ordered_by_price()
        category = {
            'pk': 0,
            'name': 'все',
        }
    else:
        category = get_category(pk)
        _products = get_products_in_category_ordered_by_price(pk)

    paginator = Paginator(_products, 2)
    try:
        products_paginator = paginator.page(page)
    except PageNotAnInteger:
        products_paginator = paginator.page(1)
    except EmptyPage:
        products_paginator = paginator.page(paginator.num_pages)

    hot_product = get_hot_product()
    same_products = get_same_products(hot_product)

    content = {
        'title': title,
        'links_menu': links_menu,
        'category': category,
        'products': products_paginator,
        'hot_product': hot_product,
        'same_products': same_products,
    }

    return render(request, 'mainapp/products_list.html', content)


def get_hot_product():
    # _products = Product.objects.filter(is_active=True, category__is_active=True)
    _products = get_products()
    # TODO: Подумать как исправить ошибку если база данных пустая
    return random.sample(list(_products), 1)[0]


def get_same_products(hot_product):
    # same_products = Product.objects.filter(is_active=True, category__is_active=True).exclude(pk=hot_product.pk)[:3]
    same_products = get_products()[:3]
    # Оптимизация sql-запросов
    # same_products = Product.objects.filter(is_active=True, category__is_active=True).exclude(pk=hot_product.pk).
    #   select_related()[:3]
    return same_products


"""
def load_from_json(file_name):
    with open(os.path.join(JSON_PATH, file_name+'.json'), 'r', errors='ignore') as infile:
        return json.load(infile)
"""


# Реализация низкоуровневого кеширования (memcached)
# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #
def get_links_menu():
    if settings.LOW_CACHE:
        key = 'links_menu'
        links_menu = cache.get(key)
        if links_menu is None:
            links_menu = ProductCategory.objects.filter(is_active=True)
            cache.set(key, links_menu)
        return links_menu
    else:
        return ProductCategory.objects.filter(is_active=True)


# noinspection DuplicatedCode
def get_category(pk):
    if settings.LOW_CACHE:
        key = f'category_{pk}'
        category = cache.get(key)
        if category is None:
            category = get_object_or_404(ProductCategory, pk=pk)
            cache.set(key, category)
        return category
    else:
        return get_object_or_404(ProductCategory, pk=pk)


def get_products():
    if settings.LOW_CACHE:
        key = 'products'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(is_active=True, category__is_active=True).select_related('category')
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(is_active=True, category__is_active=True).select_related('category')


# noinspection DuplicatedCode
def get_product(pk):
    if settings.LOW_CACHE:
        key = f'product_{pk}'
        _product = cache.get(key)
        if _product is None:
            _product = get_object_or_404(Product, pk=pk)
            cache.set(key, _product)
        return _product
    else:
        return get_object_or_404(Product, pk=pk)


def get_products_ordered_by_price():
    if settings.LOW_CACHE:
        key = 'products_ordered_by_price'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(is_active=True, category__is_active=True).order_by('price')
            cache.set(key, _products)
            return _products
        else:
            return Product.objects.filter(is_active=True, category__is_active=True).order_by('price')


def get_products_in_category_ordered_by_price(pk):
    if settings.LOW_CACHE:
        key = f'products_in_category_ordered_by_price_{pk}'
        _products = cache.get(key)
        if _products is None:
            _products = Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).\
                order_by('price')
            cache.set(key, _products)
        return _products
    else:
        return Product.objects.filter(category__pk=pk, is_active=True, category__is_active=True).order_by('price')

# # # # # # # # # # # # # # # # # # # # # # # # # # # # # #

mainapp/templates/mainapp/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
	<meta charset="utf-8">
	<title>
        {% block title %}
            {{ title|title }}
        {% endblock %}
    </title>
    {% block css %}
        <link rel="stylesheet" type="text/css" href="{% static 'css/bootstrap.min.css' %}">
        <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
        <link rel="stylesheet" href="{% static 'fonts/font-awesome/css/font-awesome.css' %}">
    {% endblock %}

    {% block js %}
        <script src="{% static 'js/jquery-3.2.1.min.js' %}"></script>
        <script src="{% static 'js/bootstrap.min.js' %}"></script>
    {% endblock %}
    {% block js_my %}
    {% endblock %}

</head>
<body>
	<div class="container">
        <div class="header">
            <div class="logo">
                <img src="{% static 'img/logo.png' %}" alt="logo">
            </div>
            {% block menu %}
            {% endblock %}
        </div>


        {% block content %}

        {% endblock %}

	</div>

    {% block footer %}
        <div class="footer">
            <hr>
            <p> Все права защищены &copy;&nbsp;{% now "Y" %} </p>
        </div>
    {% endblock %}

</body>
</html>

mainapp/templates/mainapp/cart.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    {% include 'mainapp/include/inc_main_menu.html' %}
{% endblock %}

{% block content %}
    <hr>
    <h1>Корзина</h1>
    <hr>

    <div id="goods"></div>

    <hr>

    <div id="cart">Корзина пока пуста</div>

    <div>
        Общая сумма заказа = <span id="result">0</span>
    </div>
{% endblock %}

{% block js_my %}
    <script>
        var cart = [];

        var goods = [
        {
            id: "table_orion",
            name: "Стол письменный Орион",
            price: 1000,
        },
        {
            id: "table_orion_2",
            name: "Стол письменный Орион-2",
            price: 2000,
        },
        {
            id: "table_3",
            name:"Стол письменный с ящиками №3",
            price:3000,
        }]

        function init (){
            var appDiv = document.getElementById("goods");
            var divDomElement, imgDomElement, text_name, text_price, br, btnDomElement;
            for(var good of goods){
                divDomElement = document.createElement("div");
                divDomElement.className="catalog_item";
                // Изображение товара
                imgDomElement = document.createElement("img");
                imgDomElement.src = "{% static 'img/gallery/small/' %}" + good.id+"_small.jpg";
                imgDomElement.alt = good.name;
                imgDomElement.style.width="50%";
                divDomElement.appendChild(imgDomElement);
                // Название товара
                br = document.createElement("br");
                divDomElement.appendChild(br);
                text_name = document.createTextNode(good.name);
                divDomElement.appendChild(text_name);
                // Цена товара
                br = document.createElement("br");
                divDomElement.appendChild(br);
                text_price = document.createTextNode("Цена = "+good.price);
                divDomElement.appendChild(text_price);
                // Кнопка купить
                br = document.createElement("br");
                divDomElement.appendChild(br);
                btnDomElement = document.createElement('input');
                btnDomElement.id = good.id;
                btnDomElement.type = 'button';
                btnDomElement.value = 'Купить';
                btnDomElement.style.width="50%";
                btnDomElement.onclick = addItem;
                divDomElement.appendChild(btnDomElement);
                
                appDiv.appendChild(divDomElement);
            }
        }

        function addItem(){

            var table_cart;
            var td_style = "border: 1px solid black; font-size: 150%; padding: 1px 10px"
            if (cart.length){ // Если таблица уже есть, то ищем её
                table_cart = document.querySelector('table');
            } else { // Иначе создаем новую
                table_cart = document.createElement('table');
                table_cart.style = "border-collapse: collapse;";
                var appDiv = document.getElementById("cart");
                appDiv.innerHTML = "";
                appDiv.append(table_cart);
                var row = document.createElement('tr');
                table_cart.append(row);
                var td = document.createElement('th');
                td.style = td_style;
                td.innerHTML = "Товар";
                row.append(td);
                var td = document.createElement('th');
                td.style = td_style;
                td.innerHTML = "Кол-во";
                row.append(td);
                var td = document.createElement('th');
                td.style = td_style;
                td.innerHTML = "Цена";
                row.append(td);
               var td = document.createElement('th');
                td.style = td_style;
                td.innerHTML = "Сумма";
                row.append(td);
            }

            // Находим информацию о товаре по его id
            for (var good of goods){
                if (good.id == this.id) {
                    var product_name = good.name;
                    var product_price = good.price;
                }
            }

            // Сначала изменим массив товаров в корзине
            var new_item = false;
            for (var item of cart){
                if (item.id == this.id){
                    new_item = item;
                    new_item.count += 1;
                    break;
                }
            }
            if (new_item == false){
                new_item = {};
                new_item.id = this.id;
                new_item.name = product_name;
                new_item.price = product_price;
                new_item.count = 1;
                cart.push(new_item);
            }
           
            // Затем отрисовка таблицы по данным из массива товаров в корзине
            if (new_item.count == 1){ // Только что добавили новый товар в корзину
                var row = document.createElement('tr');
                table_cart.append(row);
                            
                var td = document.createElement('td');
                td.style = td_style;
                td.innerHTML = new_item.name;
                row.append(td);

                td = document.createElement('td');                
                td.id = new_item.id + "count";
                td.style = td_style;
                td.innerHTML = new_item.count;
                row.append(td);

                td = document.createElement('td');                
                td.style = td_style;
                td.innerHTML = new_item.price;
                row.append(td);

                td = document.createElement('td');                
                td.id = new_item.id + "sum";
                td.style = td_style;
                td.innerHTML = product_price * new_item.count;
                row.append(td);
            } else { // Изменяем уже имеющийся товар

                //alert("изменим "+new_item.id + "count");

                var elementCount = document.getElementById(new_item.id + "count");
                elementCount.innerHTML = new_item.count;
                var elementSum = document.getElementById(new_item.id + "sum");
                elementSum.innerHTML = product_price * new_item.count;
            }

            var elementResult = document.getElementById("result");
            elementResult.innerHTML = countBasketPrice(cart);
        }

        function countBasketPrice(mas){         
            var result = 0;
            for(var item of mas){
                result += item.count * item.price;
            }
            return result;
        }

        window.onload = init;

    </script>

{% endblock %}

mainapp/templates/mainapp/catalog.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    {% include 'mainapp/include/inc_main_menu.html' %}
{% endblock %}

{% block content %}
    <hr>
    <h1>Каталог</h1>
    <hr>

    {% for product in products %}
        <div class="catalog_item">
            <a href="/products/{{product.id}}">
                <img src="{{ MEDIA_URL }}{{ product.image_small }}" alt="{{product.name}}" width="15%">
            </a><br>
            <a href="/products/{{product.id}}">{{product.name}}</a><br>
            <br>
            ({{product.category.name}})
        </div>
    {% endfor %}

{% endblock %}

mainapp/templates/mainapp/categories.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    {% include 'mainapp/include/inc_main_menu.html' %}
{% endblock %}

{% block content %}
    <hr>
    <h1>Категории</h1>
    <hr>

    {% for category in categories %}
        <a href="#">{{category.name}}</a>
        <br>
    {% endfor %}

{% endblock %}

mainapp/templates/mainapp/contacts.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    {% include 'mainapp/include/inc_main_menu.html' %}
{% endblock %}

{% block content %}
    <hr>
    <h1>Напишите нам</h1>

    <form action="#">
        <fieldset>
            <legend>Сообщение</legend>
            <label>Ваше имя:<input type="text" size="30" placeholder="Ваше Имя"></label><br>
            <label>Ваш Email:<input type="email" placeholder="example@mail.ru"></label><br>
            <label>Ваш телефон:<input type="tel"></label><br>
            <label>Тема сообщения:<input type="text" size="50"></label><br>
            <label>Текст сообщения:<br>
                <textarea rows="10" cols="45" name="message"></textarea>
            </label><br>
            <input type="submit" value="Отправить сообщение">
            <input type="reset" value="Отмена"><br>
        </fieldset>
    </form>

    <h2>Адрес</h2>
    <p>Контактный номер телефона интернет-магазина: <strong>+7-777-888-9944</strong></p>
    <p>Наш адрес: <strong>Маунтин-Вью, Калифорния, США</strong></p>
    <p>Наш email: <strong>besttables@examlple.com</strong></p>

    <!-- карту взял гугловую -->
    <iframe class="map"
        src="https://www.google.com/maps/embed?pb=!1m18!1m12!1m3!1d50704.098126372766!2d-122.11628637317403!3d37.413329935554!2m3!1f0!2f0!3f0!3m2!1i1024!2i768!4f13.1!3m3!1m2!1s0x808fb7495bec0189%3A0x7c17d44a466baf9b!2z0JzQsNGD0L3RgtC40L0t0JLRjNGOLCDQmtCw0LvQuNGE0L7RgNC90LjRjywg0KHQqNCQ!5e0!3m2!1sru!2sru!4v1590835347409!5m2!1sru!2sru"
        width="600" height="450" frameborder="0" style="border:0;" allowfullscreen="" aria-hidden="false" tabindex="0">
    </iframe>

{% endblock %}

mainapp/templates/mainapp/gallery.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    {% include 'mainapp/include/inc_main_menu.html' %}
{% endblock %}


{% block content %}
    <hr>
    <h1>Галерея</h1>
    <hr>

    <div class="gallery">
        {% for good in goods %}
            <img id="image>{{ good.code }}" src="{% static 'img/gallery/small/' %}{{ good.code }}_small.jpg">
        {% endfor %}
    </div>

    <div id="big_picture"></div>

{% endblock %}


{% block js_my %}

	<script>

        function changeBigPicture(eventObj){
            var appDiv = document.getElementById("big_picture");
            appDiv.innerHTML = "";
            var eventElement = eventObj.target;
            var imageNameParts = eventElement.id.split(">");
            var src = "{% static 'img/gallery/big/' %}" + imageNameParts[1] + "_big.jpg" ;
            var imageDomElement = document.createElement("img");
            imageDomElement.style.width = "50%";
            imageDomElement.src = src;
            // проверка наличия картинки по указанному в src адресу
            imageDomElement.onerror = function(){alert('фото большего размера не найдено')};
            appDiv.appendChild(imageDomElement);
        }

        function init (){
            var images = document.querySelectorAll('div.gallery > img');
            for (var i=0; i<images.length; i++){
                images[i].onclick = changeBigPicture;                
            }
            // При запуске покажем по умолчанию первую картинку
            images[0].click();
        }

        window.onload = init;

    </script>

{% endblock %}

mainapp/templates/mainapp/index.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    {% include 'mainapp/include/inc_main_menu.html' %}
{% endblock %}


{% block content %}
    <hr>
    <h1>Офисные столы Комфорт</h1>
    <p>Выбери комфортный офисный стол!<br>Отличный офисный стол - отличная произодительность труда!</p>

    <div style="float:left;" id="left"><img src="{% static 'img/left.png' %}"></div>
    <div style="float:left;width:40%" id="slider"></div>
    <div style="float:left;" id="right"><img src="{% static 'img/right.png' %}"></div>
    <div style="clear:both;"></div>
{% endblock %}


{% block js_my %}
    <script>

        var goods = [
        {
            id: "table_orion",
            name: "Стол письменный Орион",            
        },
        {
            id: "table_orion_2",
            name: "Стол письменный Орион-2",            
        },
        {
            id: "table_3",
            name:"Стол письменный с ящиками №3",            
        }]

        var i_good = 0;

        function showPicture(){
            var appDiv = document.getElementById("slider");
            appDiv.innerHTML = "";
            // Картинка
            var src = "{% static 'img/gallery/big/' %}" + goods[i_good].id + "_big.jpg";
            var imageDomElement = document.createElement("img");
            imageDomElement.style.width = "100%";
            imageDomElement.src = src;
            appDiv.appendChild(imageDomElement);
            // Название товара
            br = document.createElement("br");
            appDiv.appendChild(br);
            text_name = document.createTextNode(goods[i_good].name);
            appDiv.appendChild(text_name);            
        }
        
        function clickLeft(){
            if (i_good==0){
                i_good = goods.length-1;                
            }else{
                i_good -= 1;
            }
            showPicture();
        }

        function clickRight(){
            if (i_good==goods.length-1){
                i_good = 0;
            }else{
                i_good += 1;
            }
            showPicture();
        }

        function init(){
            var left = document.getElementById("left");
            left.onclick = clickLeft;            
            var right = document.getElementById("right");
            right.onclick = clickRight;
            showPicture();
        }

        window.onload = init;

    </script>
{% endblock %}

mainapp/templates/mainapp/product.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    {% include 'mainapp/include/inc_main_menu.html' %}
{% endblock %}

{% block content %}

    <hr>
    <h1> {{ product.name }} </h1>
    <a href="{{ MEDIA_URL }}{{ product.image }}" target="_blank">
        <img class="img_product" src="{{ MEDIA_URL }}{{ product.image }}" alt="{{product.name}}" width="20%">
    </a>

    <div class="short_desc_container">
        <h3 class="section_title">Краткое описание товара</h3>
        <p class="short_desc">
            {{ product.short_desc }}
        </p>
        <!--
        <form action="#">
            <input type="submit" class="button_buy" value="Купить">
        </form>
        -->
        <h5> Цена: {{ product.price }} </h5>
        <a href = "{% url 'basket:add' product.pk %}" class="button_buy"> Купить </a>
    </div>

    <div class="detail_desc_container">
        <h3 class="section_title">Подробное описание товара</h3>
        <p class="detail_desc">
            {{ product.description }}
        </p>
    </div>

{% endblock %}

mainapp/templates/mainapp/products_list.html
{% extends 'mainapp/base.html' %}
{% load static %}

{% block menu %}
    {% include 'mainapp/include/inc_main_menu.html' %}
{% endblock %}

{% block content %}
    <div class="details">
        <div class="links clearfix">
            {% include 'mainapp/include/inc_categories_menu.html' %}
        </div >

        <div class="products_list">
            <div class = "title clearfix">
                <h2>
                    Категория: "{{ category.name|title }}"
                </h2>

                <div class="paginator">
                    {% if products.has_previous %}
                         <a href="{% url 'products:page' category.pk products.previous_page_number %}"><</a>
                    {% endif %}
                    <span class="current">
                        страница {{ products.number }} из {{ products.paginator.num_pages }}
                    </span>
                    {% if products.has_next %}
                        <a href="{% url 'products:page' category.pk products.next_page_number %}">></a>
                    {% endif %}
                </div>

            </div>

            <br>
            <br>

            <div class = "category-products clearfix">
                {% for product in products %}
                    <div class = "catalog_item">
                        <a href="/product/{{product.id}}">
                            <img src="{{ MEDIA_URL }}{{ product.image_small }}" alt="product">
                            <div class = "text">
                                <h4> {{ product.name }} </h4>
                            </div>
                        </a>
                        <h5> Цена: {{ product.price }} </h5>
                        <a href = "{% url 'basket:add' product.pk %}" class="button_buy"> Купить </a>
                        <p> {{ product.description }} </p>
                    </div>
                {% endfor %}
            </div>
        </div>
    </div>

    <div class="clr"></div>

    <h2> Горячее предложение </h2>

     <div class = "catalog_item">
        <a href="/product/{{hot_product.id}}">
            <img src="{{ MEDIA_URL }}{{ hot_product.image_small }}" alt="hot_product">
            <div class = "text">
                <h4> {{ hot_product.name }} </h4>
            </div>
        </a>
        <h5> Цена: {{ hot_product.price }} </h5>
        <a href = "{% url 'basket:add' hot_product.pk %}" class="button_buy"> Купить </a>
        <p> {{ hot_product.description }} </p>
    </div>


    <h2> Похожие товары </h2>

    {% for product in same_products %}
        <div class = "catalog_item">
            <a href="/product/{{product.id}}">
                <img src="{{ MEDIA_URL }}{{ product.image_small }}" alt="product">
                <div class = "text">
                    <h4> {{ product.name }} </h4>
                </div>
            </a>
            <h5> Цена: {{ product.price }} </h5>
            <a href = "{% url 'basket:add' product.pk %}" class="button_buy"> Купить </a>
            <p> {{ product.description }} </p>
        </div>
    {% endfor %}


{% endblock %}